### ISSUE TITLE
Demo app - link broken

### ISSUE THREAD

**Issue by Ravsd** [maxime-tremblay/Advanced-CSS-and-JS-Techniques-to-Tweak-Your-Application-UI#2]
Would be awesome if you could fix. I got a lot of value from the Advanced CSS demo app you have

**Comment by maxime-tremblay** [comment]
Upgraded my server and the demo apps had not been imported.
Everything is now fixed.

**Comment by Ravsd** [comment]
Great, thanks a million! Keep up the good work, really appreciate having this type of reference info available…
